<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Casts\Attribute;

class QuestionSet extends Model
{
    protected $fillable = [
        'week_id', 
        'question_type_id', 
        'name', 
        'set_number', 
        'total_questions', 
        'time_limit', 
        'difficulty', 
        'is_active',
        'auto_generation_type',
        'min_digits',
        'max_digits',
        'max_number',
        'allowed_operators'
    ];
    
    protected $casts = [
        'is_active' => 'boolean',
        'allowed_operators' => 'array',
    ];
    
    public function week(): BelongsTo
    {
        return $this->belongsTo(Week::class);
    }
    
    public function questionType(): BelongsTo
    {
        return $this->belongsTo(QuestionType::class);
    }
    
    public function questions(): HasMany
    {
        return $this->hasMany(Question::class)->orderBy('question_number');
    }
    
    // Accessor for the level through week
    protected function level(): Attribute
    {
        return Attribute::make(
            get: fn() => $this->week->level
        );
    }
    
    // Get full path info
    public function getFullPathAttribute(): string
    {
        return "{$this->level->name} → Week {$this->week->week_number} → {$this->questionType->name} → {$this->name}";
    }
    
    // Check if questions are auto-generated
    public function hasAutoGeneratedQuestions(): bool
    {
        return $this->questions()->where('is_auto_generated', true)->exists();
    }
    
    // Generate questions based on settings
    public function generateQuestions(): void
    {
        if ($this->auto_generation_type === 'none') {
            return;
        }
        
        $count = $this->total_questions - $this->questions()->count();
        if ($count <= 0) {
            return;
        }
        
        $existingNumbers = $this->questions()->pluck('question_number')->toArray();
        $nextNumber = count($existingNumbers) > 0 ? max($existingNumbers) + 1 : 1;
        
        for ($i = 0; $i < $count; $i++) {
            $questionData = QuestionSetResource::generateRandomQuestion(
                $this->allowed_operators ?? ['+', '-'],
                $this->min_digits ?? 2,
                $this->max_digits ?? 3,
                $this->max_number ?? 20
            );
            
            $this->questions()->create([
                'question_type_id' => $this->question_type_id,
                'question_number' => $nextNumber++,
                'digits' => $questionData['digits'],
                'operators' => $questionData['operators'],
                'answer' => $questionData['answer'],
                'formatted_question' => $questionData['formatted'],
                'is_auto_generated' => true,
            ]);
        }
    }
    
    // Update total questions count based on actual questions
    public function updateTotalQuestions(): void
    {
        $this->total_questions = $this->questions()->count();
        $this->save();
    }
}